### ISSUE TITLE
Mistake in example on NPM

### ISSUE THREAD

**Issue by lhansford** [kdelmonte/gulp-multi-dest#1]
The code example on NPM doesn't actually use gulp-multi-dest. Took a few minutes for me to figure out why it wasn't working :)

`gulp.task('copy', function() {
  return gulp.src('./js/*.js')
    .pipe(gulp.dest(['./dist1/js', './dist2/js'], destOptions));
});`

Thanks for this great little plugin!

**Comment by kdelmonte** [comment]
I am glad you find it useful.

I noticed that on the repo a while ago and fixed it but never published to npm. It is fixed now. Thanks for reporting it.
